local colors = require('schemes.van.palette')

local ts = {
	['@annotation']                 = { fg = colors.Rose20, bold = true },
	['@attribute']                  = { fg = colors.Rose20, bold = true },
	['@boolean']                    = { fg = colors.Wine12, bold = true },
	['@character']                  = { fg = colors.Coral16, bold = true },
	['@character.printf']           = { fg = colors.Coral16, bold = true },
	['@character.special']          = { fg = colors.Orange12, bold = true },
	['@comment']                    = { fg = colors.Gray8 },
	['@comment.error']              = { fg = colors.Gray8 },
	['@comment.hint']               = { fg = colors.Gray8 },
	['@comment.info']               = { fg = colors.Gray8 },
	['@comment.note']               = { fg = colors.Gray8 },
	['@comment.todo']               = { fg = colors.Gray8 },
	['@comment.warning']            = { fg = colors.Gray8 },
	['@constant']                   = { fg = colors.Azure12 },
	['@constant.builtin']           = { fg = colors.Cyan8 },
	['@constant.macro']             = { fg = colors.Capri12 },
	['@constructor']                = { fg = colors.Cyan8 },
	['@constructor.tsx']            = { fg = colors.Cyan8 },
	['@diff.delta']                 = { fg = colors.Orange12 },
	['@diff.minus']                 = { fg = colors.Red4 },
	['@diff.plus']                  = { fg = colors.Blue16 },
	['@function']                   = { fg = colors.Blue16 },
	['@function.builtin']           = { fg = colors.Cobalt8 },
	['@function.call']              = { fg = colors.Blue12 },
	['@function.macro']             = { fg = colors.Indigo12 },
	['@function.method']            = { fg = colors.Blue16 },
	['@function.method.call']       = { fg = colors.Blue12 },
	['@keyword']                    = { fg = colors.Gray24, bold = true },
	['@keyword.coroutine']          = { fg = colors.Capri20, bold = true },
    ['@keyword.conditional']        = { fg = colors.Rose20, bold = true },
	['@keyword.debug']              = { fg = colors.Orchid20, bold = true },
	['@keyword.directive']          = { fg = colors.Cobalt20, bold = true },
	['@keyword.directive.define']   = { fg = colors.Cobalt20, bold = true },
	['@keyword.exception']          = { fg = colors.Red20, bold = true },
	['@keyword.function']           = { fg = colors.Blue20, bold = true },
	['@keyword.import']             = { fg = colors.Raspberry20, bold = true },
	['@keyword.operator']           = { fg = colors.Rose20, bold = true },
	['@keyword.repeat']             = { fg = colors.Orange20, bold = true },
	['@keyword.return']             = { fg = colors.Blue20, bold = true },
	['@keyword.storage']            = { fg = colors.Gray24, bold = true },
	['@label']                      = { fg = colors.Gray24, bold = true },
	['@markup']                     = { fg = colors.Gray16 },
	['@markup.emphasis']            = { fg = colors.Gray24 },
	['@markup.environment']         = { fg = colors.Gray24 },
	['@markup.environment.name']    = { fg = colors.Gray24 },
	['@markup.heading']             = { fg = colors.Gray16, bold = true },
	['@markup.italic']              = { italic = true },
	['@markup.link']                = { fg = colors.Gray12 },
	['@markup.link.label']          = { fg = colors.Gray16 },
	['@markup.link.label.symbol']   = { fg = colors.Yellow16 },
	['@markup.link.url']            = { fg = colors.Blue16 },
	['@markup.list']                = { fg = colors.Gray16 },
	['@markup.list.checked']        = { fg = colors.Lime12 },
	['@markup.list.markdown']       = { fg = colors.Amethyst8 },
	['@markup.list.unchecked']      = { fg = colors.Gray12 },
	['@markup.math']                = { fg = colors.Yellow12 },
	['@markup.raw']                 = { fg = colors.Gray24 },
	['@markup.raw.markdown_inline'] = { fg = colors.Gray24 },
	['@markup.strikethrough']       = { strikethrough = true },
	['@markup.strong']              = { bold = true },
	['@markup.underline']           = { underline = true },
	['@module']                     = { fg = colors.Raspberry12 },
	['@module.builtin']             = { fg = colors.Rose8 },
	['@namespace.builtin']          = { fg = colors.Rose16, bold = true },
	['@none']                       = { fg = colors.Gray16 },
	['@number']                     = { fg = colors.Orange12 },
	['@number.float']               = { fg = colors.Yellow12 },
	['@operator']                   = { fg = colors.Rose20, bold = true },
	['@property']                   = { fg = colors.Gray24 },
	['@punctuation.bracket']        = { fg = colors.Cyan8 },
	['@punctuation.delimiter']      = { fg = colors.Gray20 },
	['@punctuation.special']        = { fg = colors.Rose20},
	['@string']                     = { fg = colors.Red8 },
	['@string.documentation']       = { fg = colors.Red12 },
	['@string.escape']              = { fg = colors.Red16 },
	['@string.regexp']              = { fg = colors.Coral12 },
	['@tag']                        = { fg = colors.Gray24, bold = true },
	['@tag.attribute']              = { fg = colors.Aqua12 },
	['@tag.delimiter']              = { fg = colors.Cyan8 },
	['@tag.delimiter.tsx']          = { fg = colors.Cyan8 },
	['@tag.tsx']                    = { fg = colors.Gray24, bold = true },
	['@tag.javascript']             = { fg = colors.Gray24, bold = true },
	['@type']                       = { fg = colors.Orchid12 },
	['@type.builtin']               = { fg = colors.Magenta8 },
	['@type.definition']            = { fg = colors.Amethyst16 },
	['@type.qualifier']             = { fg = colors.Amethyst12 },
	['@variable']                   = { fg = colors.Aqua12 },
	['@variable.builtin']           = { fg = colors.Sky8 },
	['@variable.member']            = { fg = colors.Mint12 },
	['@variable.parameter']         = { fg = colors.Aqua12 },
	['@variable.parameter.builtin'] = { fg = colors.Sky8 },
}

return ts
